spring.application.name=events
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/event_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring Security default admin
# Spring Security default admin
spring.security.user.name=Hari 
spring.security.user.password=h123456
spring.security.user.roles=ADMIN

# Email Configuration (SMTP)
spring.mail.host=aharshith65@gmail.com
spring.mail.port=587
spring.mail.username=Harshith_Reddy
spring.mail.password=Hari24669
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
